### ISSUE TITLE
Create a working MLC digital collection page for demo

### ISSUE THREAD

**Issue by bufordrat** [uchicago-library/library_website#686]
# Goal

The goal for this issue is to create a demonstration version of the MLC digital collections page, following the front-end design given here:

https://www.figma.com/file/JiQC9sndlmOvhimxxW9Dty/MLP-UX-Protoypes

The demonstration version will run from its own branch on our test server, without yet attempting to cleanly integrate with Social Scientists Map Chicago.  (That will be pursued in a later issue, once we backport Social Scientists Map Chicago to use Mark Logic rather than IIIF to supply the data underlying cluster and list browes.  Once this new design is in place, a browse will simply be a search results page with the search term pre-populated.)

# Features

This demo will feature:

- all the MLC recordings, each one on an object page
- viewability permissions that vary from item to item
- series pages in addition to object pages
- an embedded player using Panopto for audio streaming

# TODOs

- [ ] create landing page
- [ ] create series route/template
- [ ] determine how Mark Logic information is to be represented in the Wagtail DB
- [ ] create object page
- [ ] sensibly manage permissions on object page
